### ISSUE TITLE
Add detailed gunicorn config, to pass along access and error logs, work async, etc.

### ISSUE THREAD

**Issue by ghost** [nerium-data/nerium#13]

**Comment by tym-xqo** [comment]
The original Dockerfile already was doing this -- gunicorn invoked with `--log-file=-`

**Comment by ghost** [comment]
Huh, I guess I was not familiar with that syntax, also we weren't seeing logs, but also that might not have been gunicorn, can we confirm?

**Comment by tym-xqo** [comment]
Gunicorn doesn't log much beyond worker startup without additional config. I'll change the name of this issue to add more detailed log info.

**Comment by tym-xqo** [comment]
One more change struck me as wanted here

**Comment by tym-xqo** [comment]
It's a general Gunicorn config addition that's needed here, really

**Comment by ghost** [comment]
Yep that would be lovely.

**Comment by tym-xqo** [comment]
#22
