### ISSUE TITLE
Switch all Reporting Platform components to Apache 2.0 license

### ISSUE THREAD

**Issue by tym-xqo** [nerium-data/nerium#18]
I'm starting to think about what needs to happen to make the Reporting Platform fully public — by which, for clarity, we'll say means pushing semantically versioned releases to major public package repositories (e.g., PyPi, npm, Docker Hub). As the product of a commercial venture itself, and in the interest of wider adoption, the copyleft requirements of the GPL aren't appropriate. Among non-copyleft, permissive, "pushover" licenses, Apache 2.0 is the [recommendation of the FSF](https://www.gnu.org/licenses/license-recommendations.html) and their reasoning looks sound to me. I also notice that it seems to be popular among the caliber and type of projects that I'd like to be playing among, — viz. Luigi, Superset, &c.

**Comment by ghost** [comment]
I'm a fan of Apache 2.0

**Comment by henryrizzi** [comment]
That sounds like a good idea to me as well.

**Comment by tym-xqo** [comment]
https://github.com/OAODEV/nerium/commit/88fb89f5398cb7c59b2162a1d041541f1e5a1cce
