### ISSUE TITLE
Put format in the path instead of the slightly awkward query param

### ISSUE THREAD

**Issue by jessebmiller** [nerium-data/nerium#36]
I was thinking about this and it occurred to me that the format could be specified as an optional extension to the path rather than using the awkward `ne_format` query param

`/v1/query/<query-name>?a=b` would use the default formatter while
`/v1/query/<query-name>/toml?a=b` would use the toml formatter

**Comment by tym-xqo** [comment]
@jessebmiller It was [originally that way](https://github.com/OAODEV/nerium/blob/7d063560d0fd329feb476ce366534456c2a51258/nerium.py#L139); I'm not clear offhand why we changed that.

**Comment by jessebmiller** [comment]
I can't remember why we did either.

The optional query type prefix does seem to add complexity though. with those three options you can only specify the format if you also specify the query type.

**Comment by tym-xqo** [comment]
Yeah, I do remember having to address the latter issue. In more recent versions of the api, that prefix is entirely unnecessary and was removed from the routing. In any case, I agree that having the format in the path is a preferable scheme, and will try to work that in soon.

**Comment by tym-xqo** [comment]
[#37](https://github.com/OAODEV/nerium/pull/37)
