### ISSUE TITLE
500 INTERNAL SERVER ERROR in Takei Line Item Endpoint Responses

### ISSUE THREAD

**Issue by luzmcosta** [nerium-data/nerium#4]
A `500 INTERNAL SERVER ERROR` precedes the `200 OK` response from the following query:

`http 'http://nerium-takei:8081/v1/takei/takei-line-item-history/affix/?client_id={$client_id}&ad_id={$ad_id}'`

**Comment by tym-xqo** [comment]
@luzmcosta I can't point to a specific commit with a fix, but I am no longer able to reproduce this. I'm going to close for now. If you still see the issue, let me know.
