### ISSUE TITLE
301 MOVED PERMANENTLY Responses Heard as Errors at Takei Organizations Endpoint

### ISSUE THREAD

**Issue by luzmcosta** [nerium-data/nerium#5]
At the "takei organizations" endpoint, I noticed query strings and the base path to the `affix` endpoint both return a 301 MOVED PERMANENTLY instead of whatever the more appropriate response would be. Addressing these points will allow the front end to handle things a bit better should the JS or browser behavior lead to breaks in those ways.

```
HTTP/1.1 301 MOVED PERMANENTLY
Connection: close
Content-Length: 315
Content-Type: text/html; charset=utf-8
Date: Mon, 22 Jan 2018 18:06:13 GMT
Location: http://nerium-takei:8081/v1/takei/takei-organizations/
Server: gunicorn/19.7.1

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="http://nerium-takei:8081/v1/takei/takei-organizations/">http://nerium-takei:8081/v1/takei/takei-organizations/</a>.  If not click the link.
```

**Comment by henryrizzi** [comment]
I think I found a more graceful way to handle the url deciphering related stuff. Just pushed something to the branch I'm currently working on to not break redirection for non`/` terminating url.
https://github.com/OAODEV/nerium/blob/modularized/app.py#L85 
^this seems to solve that issue^
