### ISSUE TITLE
Set Uncaught Exceptions' JSON Responses

### ISSUE THREAD

**Issue by luzmcosta** [nerium-data/nerium#6]
If nerium can capture uncaught exceptions, most often seen as "Internal Server Error" messages, that would allow the client to manage these errors like any other, by looking at the `error` property. As is, the JS will need to take this potential response into account repeatedly, at the expense of maintainability and, potentially, performance.

`http 'http://nerium-takei:8081/v1/takei/takei-orders/affix/?client_id=361&advertiser_name=Visa'`

```
HTTP/1.1 500 INTERNAL SERVER ERROR
Connection: close
Content-Length: 37
Content-Type: application/json
Date: Mon, 22 Jan 2018 17:38:02 GMT
Server: gunicorn/19.7.1

{
    "message": "Internal Server Error"
}
```

**Comment by tym-xqo** [comment]
@luzmcosta Nerium actually does have some graceful error handling, but it's hard to catch exceptions on, say, the exception handler itself. Flask does allow for this sort of global error handler (see for example https://stackoverflow.com/questions/29332056/global-error-handler-for-any-exception/41655397#41655397) and I can see why having this in an `error` object even if it's still just a generic 500 would be at least a bit more graceful. Thanks for the note!

**Comment by tym-xqo** [comment]
I'm not sure we've got handling for _every_ contingency, but have added 400s for everything that we've seen in practice, and a catchall that reformats any remaining 500s to JSON. If anything else pops up please start a new issue, but closing this for now.

**Comment by tym-xqo** [comment]
https://github.com/OAODEV/nerium/pull/22
